# Generated by Django 4.1.5 on 2023-01-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='image',
            field=models.ImageField(default='empty.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
