# Generated by Django 3.2.9 on 2023-01-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_message_name_alter_message_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
